### ISSUE TITLE
add cheat sheet for the workshop

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/ecology-workshop#1]
It might be nice to have a two page (1 page, 2 sided) cheat sheet for the topics in this workshop. There could be a 'Tidy Data' section, an 'Open Refine' section, an R or Python section and an SQL section.

This is a nice start on an SQL one
http://www.sql-tutorial.net/SQL-Cheat-Sheet.pdf

Although it might make more sense to have a cheat sheet per topic, so things are more modular, and the cheat sheet stays with the topic.

**Comment by ethanwhite** [comment]
We do have an SQL Cheat Sheet:
https://github.com/datacarpentry/sql-ecology/blob/gh-pages/sql_cheat_sheet.md

that might be useful as a starting point.

I'm torn on 1 vs many. I do like the idea that you go home with a single sheet cheat sheet of everything we've taught, but as you note keeping it with content would be easier to maintain.

**Comment by ErinBecker** [comment]
Closing this as outdated.
