### ISSUE TITLE
add information about installing tidyverse and RSQLite for mac and windows

### ISSUE THREAD

**Issue by marwahaha** [datacarpentry/ecology-workshop#32]
I am teaching a remote workshop starting this week and a learner scheduled time with me because they were stuck on the instructions: https://datacarpentry.org/ecology-workshop/setup-r-workshop.html

They were stuck because on a Windows machine, there were no instructions to install tidyverse and RSQLite packages, even though the beginning of the section says
>  R and RStudio are separate downloads and installations. R is the underlying statistical computing environment, but using R alone is no fun. RStudio is a graphical integrated development environment (IDE) that makes using R much easier and more interactive. You need to install R before you install RStudio. After installing both programs, you will need to install some specific R packages within RStudio. Follow the instructions below for your operating system, and then follow the instructions to install tidyverse and RSQLite.

I recommend adding the instructions from Linux (copy-pasted below) in all sections, or adding another subheading to clarify this point.
> After installing R and RStudio, you need to install the tidyverse and RSQLite packages. Start RStudio by double-clicking the icon and then type: install.packages(c("tidyverse", "RSQLite")). You can also do this by going to Tools -> Install Packages and typing the names of the packages you want to install, separated by a comma.

**Comment by fmichonneau** [comment]
Thanks for bringing this up @marwahaha!
