### ISSUE TITLE
Inconsistent formatting between lessons

### ISSUE THREAD

**Issue by amkatzer** [datacarpentry/ecology-workshop#38]
When looking through the different lessons listed in the overview, there is a consistent formatting style that is followed by all of the lessons except the Data Analysis and Visualization in R for Ecologists section. Having consistency between all of the lessons may improve reading/navigation speed when switching between lessons.

**Comment by zkamvar** [comment]
Hi @amkatzer,

Thank you for opening this issue! I'm happy to let you know that we are on it! 

In short, we are going to be migrating all of our lessons to use [The Carpentries Workbench lesson infrastructure](https://carpentries.org/blog/2022/01/live-lesson-infrastructure/) in January 2023, which means that all of the lessons will have the same styling and be guaranteed to be up-to-date.  

For context on this particular workshop: two of the lessons are going to be undergoing beta testing for The Workbench
https://github.com/carpentries/workbench/discussions/11

**Comment by amkatzer** [comment]
Awesome! Thanks so much for the information and links.

**Comment by ErinBecker** [comment]
Closing this as all lessons now use the Workbench!
